<?php use UniMapper\NamingConvention as UNC; ?>
<table>
    <thead>
        <tr><th colspan="2">Config</th></tr>
    </thead>
    <tbody>
        <tr>
            <td>API</td>
            <td><?php echo $this->config["api"]["enabled"] ? "<strong>Enabled</strong>" : "Disabled" ?></td>
        </tr>
        <?php if ($this->config["api"]["enabled"]): ?>
        <tr>
            <td>API Module</td>
            <td><?php echo $this->config["api"]["module"] ?>:</td>
        </tr>
        <?php endif ?>
        <tr>
            <td>Cache</td>
            <td><?php echo $this->config["cache"] ? "<strong>Enabled</strong>" : "Disabled" ?></strong></td>
        </tr>
        <tr>
            <td>Entity namespace</td>
            <td><?php echo UNC::$entityMask ?></td>
        </tr>
        <tr>
            <td>Repository namespace</td>
            <td><?php echo UNC::$repositoryMask ?></td>
        </tr>
        <?php if ($this->config["customQueries"]): ?>
        <tr>
            <td>Custom queries</td>
            <td>
                <ul>
                    <?php foreach ($this->config["customQueries"] as $customQuery): ?>
                        <li><?php echo $customQuery ?></li>
                    <?php endforeach ?>
                </ul>
            </td>
        </tr>
        <?php endif ?>
    </tbody>
</table>