<?php
use UniMapper\NamingConvention as NC;
?>
<h1>UniMapper queries</h1>
<div class="nette-inner">
    <table>
        <thead>
            <th>Elapsed time</th>
            <th>Repository</th>
            <th>Query</th>
            <th>Result</th>
        </thead>
        <tbody>
        <?php foreach ($this->repositories as $repositoryIndex => $repository): ?>
            <?php foreach ($repository->getLogger()->getQueries() as $queryIndex => $query): ?>
                <?php $index = $repositoryIndex . "-" . $queryIndex ?>
                <?php if ($query->result !== null): ?>
                <tr>
                    <td><?php echo round($query->elapsed, 3) ?> ms</td>
                    <td><?php echo $repository->getName() ?></td>
                    <td>
                        <?php include __DIR__ . '/queries.phtml' ?>
                    </td>
                    <td>
                        <!-- result -->
                        <?php if ($query->result instanceof \UniMapper\EntityCollection): ?>
                            <?php if (count($query->result) === 0): ?>
                                [0] <?php echo NC::classToName($query->result->getEntityClass(), NC::$entityMask) ?>
                            <?php else: ?>
                                <a href="#unimapper-panel-result-<?php echo $index ?>" class="nette-toggler nette-toggle-collapsed" rel="#unimapper-panel-result-<?php echo $index ?>">
                                    [<?php echo count($query->result) ?>]
                                    <?php echo NC::classToName($query->result->getEntityClass(), NC::$entityMask) ?>
                                </a>
                                <div id="unimapper-panel-result-<?php echo $index ?>" class="nette-collapsed">
                                    <?php foreach ($query->result as $entity) { ?>
                                        <?php echo $this->getClickable($entity->getData(), true) ?>
                                    <?php } ?>
                                </div>
                            <?php endif ?>
                        <?php elseif ($query->result instanceof \UniMapper\Entity): ?>
                            <a href="#unimapper-panel-result-<?php echo $index ?>" class="nette-toggler nette-toggle-collapsed" rel="#unimapper-panel-result-<?php echo $index ?>"><?php echo NC::classToName(get_class($query->result), NC::$entityMask) ?></a>
                            <div id="unimapper-panel-result-<?php echo $index ?>" class="nette-collapsed">
                                <?php echo $this->getClickable($query->result->getData(), true) ?>
                            </div>
                        <?php else: ?>
                            <?php echo $this->getClickable($query->result, true) ?>
                        <?php endif ?>
                    </td>
                </tr>
                <?php endif ?>
            <?php endforeach ?>
        <?php endforeach ?>
        </tbody>
    </table>
</div>