<?php use UniMapper\Query ?>
<a href="#unimapper-panel-query-<?php echo $index ?>" class="tracy-toggle tracy-collapsed nette-toggler nette-toggle-collapsed" rel="#unimapper-panel-query-<?php echo $index ?>">
    <strong><?php echo $query->getName() ?></strong>
</a>
<div id="unimapper-panel-query-<?php echo $index ?>" class="tracy-collapsed nette-collapsed">
    <?php if ($query instanceof Query\Find): ?>
        <table>
            <?php include __DIR__ . '/queries/selection.phtml' ?>
            <?php include __DIR__ . '/queries/conditions.phtml' ?>
            <?php include __DIR__ . '/queries/limit.phtml' ?>
            <?php include __DIR__ . '/queries/offset.phtml' ?>
            <?php include __DIR__ . '/queries/orderBy.phtml' ?>
            <?php if ($query->cachedOptions): ?>
                <tr>
                    <th>Cache options</th>
                    <td>
                        <?php echo $this->_getClickable($query->cachedOptions, true) ?>
                    </td>
                </tr>
            <?php endif ?>
        </table>
    <?php elseif ($query instanceof Query\Associate): ?>
        <table>
            <tr>
                <th>Primary value</th>
                <td>
                    <?php echo $query->primaryValue ?>
                </td>
            </tr>
            <tr>
                <th>Association</th>
                <td><?php echo $this->_getClickable($query->association, true) ?></td>
            </tr>
        </table>
    <?php elseif ($query instanceof Query\FindOne || $query instanceof Query\DeleteOne): ?>
        <table>
            <tr>
                <th>Primary value</th>
                <td>
                    <?php echo $query->primaryValue ?>
                </td>
            </tr>
        </table>
    <?php elseif ($query instanceof Query\Count): ?>
        <table>
            <?php include __DIR__ . '/queries/conditions.phtml' ?>
        </table>
    <?php elseif ($query instanceof Query\Delete): ?>
        <table>
            <?php include __DIR__ . '/queries/conditions.phtml' ?>
        </table>
    <?php elseif ($query instanceof Query\Insert): ?>
        <table>
            <tr>
                <th>Values</th>
                <td><?php echo $this->_getClickable($query->entity->getData(), true) ?></td>
            </tr>
        </table>
    <?php elseif ($query instanceof Query\Update): ?>
        <table>
            <?php include __DIR__ . '/queries/conditions.phtml' ?>
            <tr>
                <th>Data</th>
                <td><?php echo $this->_getClickable($query->entity->getData(), true) ?></td>
            </tr>
        </table>
    <?php elseif ($query instanceof Query\UpdateOne): ?>
        <table>
            <tr>
                <th>Primary value</th>
                <td>
                    <?php echo $query->primaryValue ?>
                </td>
            </tr>
            <tr>
                <th>Data</th>
                <td><?php echo $this->_getClickable($query->entity->getData(), true) ?></td>
            </tr>
        </table>
    <?php endif ?>
</div>