<?php if ($query instanceof \UniMapper\Query\Custom): ?>
    <a href="#unimapper-panel-query-<?php echo $index ?>" class="nette-toggler nette-toggle-collapsed" rel="#unimapper-panel-query-<?php echo $index ?>">
        <strong>custom</strong>
    </a>
    <div id="unimapper-panel-query-<?php echo $index ?>" class="nette-collapsed">
        <table>
            <tr>
                <th>Mapper</th>
                <td><?php echo $query->mapper->getName() ?></td>
            </tr>
            <tr>
                <th>Method</th>
                <td><?php echo $query->method ?></td>
            </tr>
            <tr>
                <th>Query</th>
                <td><?php echo $query->query ?></td>
            </tr>
            <?php if ($query->data): ?>
            <tr>
                <th>Data</th>
                <td><?php echo $this->getClickable($query->data, true) ?></td>
            </tr>
            <?php endif ?>
        </table>
    </div>
<?php elseif ($query instanceof \UniMapper\Query\FindAll): ?>
    <a href="#unimapper-panel-query-<?php echo $index ?>" class="nette-toggler nette-toggle-collapsed" rel="#unimapper-panel-query-<?php echo $index ?>">
        <strong>findAll</strong>
    </a>
    <div id="unimapper-panel-query-<?php echo $index ?>" class="nette-collapsed">
        <table>
            <?php include __DIR__ . '/queries/selection.phtml' ?>
            <?php include __DIR__ . '/queries/conditions.phtml' ?>
            <?php include __DIR__ . '/queries/limit.phtml' ?>
            <?php include __DIR__ . '/queries/offset.phtml' ?>
            <?php include __DIR__ . '/queries/orderBy.phtml' ?>
        </table>
    </div>
<?php elseif ($query instanceof \UniMapper\Query\FindOne): ?>
    <a href="#unimapper-panel-query-<?php echo $index ?>" class="nette-toggler nette-toggle-collapsed" rel="#unimapper-panel-query-<?php echo $index ?>">
        <strong>findOne</strong>
    </a>
    <div id="unimapper-panel-query-<?php echo $index ?>" class="nette-collapsed">
        <table>
            <tr>
                <th>Primary value</th>
                <td>
                    <?php echo $query->primaryValue ?>
                </td>
            </tr>
        </table>
    </div>
<?php elseif ($query instanceof \UniMapper\Query\Count): ?>
    <a href="#unimapper-panel-query-<?php echo $index ?>" class="nette-toggler nette-toggle-collapsed" rel="#unimapper-panel-query-<?php echo $index ?>">
        <strong>count</strong>
    </a>
    <div id="unimapper-panel-query-<?php echo $index ?>" class="nette-collapsed">
        <table>
            <?php include __DIR__ . '/queries/conditions.phtml' ?>
        </table>
    </div>
<?php elseif ($query instanceof \UniMapper\Query\Delete): ?>
    <a href="#unimapper-panel-query-<?php echo $index ?>" class="nette-toggler nette-toggle-collapsed" rel="#unimapper-panel-query-<?php echo $index ?>-">
        <strong>delete</strong>
    </a>
    <div id="unimapper-panel-query-<?php echo $index ?>" class="nette-collapsed">
        <table>
            <?php include __DIR__ . '/queries/conditions.phtml' ?>
        </table>
    </div>
<?php elseif ($query instanceof \UniMapper\Query\Insert): ?>
    <a href="#unimapper-panel-query-<?php echo $index ?>" class="nette-toggler nette-toggle-collapsed" rel="#unimapper-panel-query-<?php echo $index ?>">
        <strong>insert</strong>
    </a>
    <div id="unimapper-panel-query-<?php echo $index ?>" class="nette-collapsed">
        <table>
            <tr>
                <th>Data</th>
                <td><?php echo $this->getClickable($query->entity->getData(), true) ?></td>
            </tr>
        </table>
    </div>
<?php elseif ($query instanceof \UniMapper\Query\Update): ?>
    <a href="#unimapper-panel-query-<?php echo $index ?>" class="nette-toggler nette-toggle-collapsed" rel="#unimapper-panel-query-<?php echo $index ?>">
        <strong>update</strong>
    </a>
    <div id="unimapper-panel-query-<?php echo $index ?>" class="nette-collapsed">
        <table>
            <?php include __DIR__ . '/queries/conditions.phtml' ?>
            <tr>
                <th>Data</th>
                <td><?php echo $this->getClickable($query->entity->getData(), true) ?></td>
            </tr>
        </table>
    </div>
<?php endif ?>