<table>
    <thead>
        <tr><th colspan="2">Config</th></tr>
    </thead>
    <tbody>
        <tr>
            <td>Cache</td>
            <td><?php echo $this->config["cache"] ? "<strong>Enabled</strong>" : "Disabled" ?></strong></td>
        </tr>
        <tr>
            <td>Entity namespace</td>
            <td><?php echo \UniMapper\Convention::getMask(\UniMapper\Convention::ENTITY_MASK) ?></td>
        </tr>
        <tr>
            <td>Repository namespace</td>
            <td><?php echo \UniMapper\Convention::getMask(\UniMapper\Convention::REPOSITORY_MASK) ?></td>
        </tr>
        <?php if ($this->config["customQueries"]): ?>
        <tr>
            <td>Custom queries</td>
            <td>
                <ul>
                    <?php foreach ($this->config["customQueries"] as $customQuery): ?>
                        <li><?php echo $customQuery ?></li>
                    <?php endforeach ?>
                </ul>
            </td>
        </tr>
        <?php endif ?>
    </tbody>
</table>