<style type="text/css">
    #tracy-debug .tracy-panel table,
    #nette-debug .nette-panel table {
        margin-bottom: 10px;
    }
    #tracy-debug .tracy-panel table td,
    #nette-debug .nette-panel table td {
        list-style-type: none;
    }
    #tracy-debug .tracy-panel .unimapper-panel-label,
    #nette-debug .nette-panel .unimapper-panel-label {
        border-radius: 0.25em;
        text-align: center;
        vertical-align: baseline;
        white-space: nowrap;
        padding: 0.2em 0.6em 0.3em;
        display: inline;
        font-size: 75%;
        font-weight: 700;
        line-height: 1;
        background-color: #777;
        color: #fff;
    }
    #tracy-debug .tracy-panel .unimapper-panel-elapsed,
    #nette-debug .nette-panel .unimapper-panel-elapsed {
         text-align: right;
    }
    #tracy-debug .tracy-panel .unimapper-panel-progressbar,
    #nette-debug .nette-panel .unimapper-panel-progressbar {
        text-align: center;
        height: 20px;
        overflow: hidden;
        box-sizing: border-box;
        box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1) inset;
        background-color: #f5f5f5;
    }
    #tracy-debug .unimapper-panel-progressbar .demands-level-low,
    #nette-debug .unimapper-panel-progressbar .demands-level-low {
         background-color: #5cb85c;
    }
    #tracy-debug .unimapper-panel-progressbar .demands-level-medium,
    #nette-debug .unimapper-panel-progressbar .demands-level-medium {
        background-color: #f0ad4e;
    }
    #tracy-debug .unimapper-panel-progressbar .demands-level-high,
    #nette-debug .unimapper-panel-progressbar .demands-level-high {
        background-color: #d9534f;
    }
    #tracy-debug .unimapper-panel-progressbar > div,
    #nette-debug .unimapper-panel-progressbar > div {
        text-align: center;
        box-shadow: 0 -1px 0 rgba(0, 0, 0, 0.15) inset;
        float: left;
        height: 100%;
        line-height: 20px;
        background-color: #428bca;
        color: #fff;
    }
</style>

<h1>UniMapper</h1>
<div class="nette-inner tracy-inner">
    <div id="unimapper-panel-queries">
        <?php include __DIR__ . '/queries.phtml' ?>
    </div>
    <a href="#unimapper-panel-config" rel="#unimapper-panel-config" class="tracy-toggle tracy-collapsed nette-toggler nette-toggle-collapsed">Config</a>
    <div id="unimapper-panel-config" class="tracy-collapsed nette-collapsed">
        <?php include __DIR__ . '/config.phtml' ?>
    </div>
</div>