<?php

use UniMapper\NamingConvention as UNC;

$uid = uniqid();
$elapsed = $this->_getElapsed(); ?>

<table>
    <thead>
        <th>Elapsed time</th>
        <th>Demands</th>
        <th>Query</th>
        <th>Adapter queries</th>
        <th>Result</th>
    </thead>
    <tbody>
        <?php foreach ($this->queryBuilder->getCreated() as $index => $query): ?>
            <?php $index .= "-" . $uid ?>
            <?php if ($query->executed): ?>
            <tr>
                <td class="unimapper-panel-elapsed"><?php echo round($query->elapsed * 1000, 2) ?> ms</td>
                <td>
                    <?php
                        $queryLevel = $this->_getQueryLevel($elapsed, $query->elapsed);
                        if ($queryLevel > 80) {
                            $demands = "high";
                        } elseif ($queryLevel <= 80 && $queryLevel >= 40) {
                            $demands = "medium";
                        } else {
                            $demands = "low";
                        }
                    ?>
                    <div class="unimapper-panel-progressbar">
                       <div class="demands-level-<?php echo $demands ?>" style="width: <?php echo $queryLevel  ?>%"></div>
                    </div>
                </td>
                <td><?php include __DIR__ . '/queries/detail.phtml' ?></td>
                <td>
                    <?php if ($query instanceof \UniMapper\Query\Find && $query->cached): ?>
                        <span class="unimapper-panel-label" style="background-color: #428bca; color: #fff;">Cached</span>
                    <?php else: ?>
                        <span class="unimapper-panel-label"><?php echo count($query->adapterQueries) ?></span>
                        <a href="#unimapper-panel-adapter-queries-<?php echo $index ?>" class="tracy-toggle tracy-collapsed nette-toggler nette-toggle-collapsed" rel="#unimapper-panel-adapter-queries-<?php echo $index?>"></a>
                        <div id="unimapper-panel-adapter-queries-<?php echo $index ?>" class="nette-collapsed tracy-collapsed">
                            <?php foreach ($query->adapterQueries as $adapterQuery): ?>
                                <pre class="nette-dump tracy-dump"><span class="nette-dump-string tracy-dump-string"><?php echo $adapterQuery ?></span></pre>
                            <?php endforeach ?>
                        </div>
                    <?php endif ?>
                </td>
                <td>
                    <!-- result -->
                    <?php if ($query->result instanceof \UniMapper\EntityCollection): ?>
                        <?php if (count($query->result) === 0): ?>
                            [0] <?php echo UNC::classToName($query->result->getEntityReflection()->getClassName(), UNC::$entityMask) ?>
                        <?php else: ?>
                            <span class="unimapper-panel-label"><?php echo count($query->result) ?></span>
                            <a href="#unimapper-panel-result-<?php echo $index ?>" class="tracy-toggle tracy-collapsed nette-toggler nette-toggle-collapsed" rel="#unimapper-panel-result-<?php echo $index ?>">
                                <?php echo UNC::classToName($query->result->getEntityReflection()->getClassName(), UNC::$entityMask) ?>
                            </a>
                            <div id="unimapper-panel-result-<?php echo $index ?>" class="nette-collapsed tracy-collapsed">
                                <?php foreach ($query->result as $entity) { ?>
                                    <?php echo $this->_getClickable($entity->toArray(true), true) ?>
                                <?php } ?>
                            </div>
                        <?php endif ?>
                    <?php elseif ($query->result instanceof \UniMapper\Entity): ?>
                        <a href="#unimapper-panel-result-<?php echo $index ?>" class="tracy-toggle tracy-collapsed nette-toggler nette-toggle-collapsed" rel="#unimapper-panel-result-<?php echo $index. $uid ?>"><?php echo UNC::classToName(get_class($query->result), UNC::$entityMask) ?></a>
                        <div id="unimapper-panel-result-<?php echo $index ?>" class="nette-collapsed tracy-collapsed">
                            <?php echo $this->_getClickable($query->result->toArray(true), true) ?>
                        </div>
                    <?php else: ?>
                        <?php echo $this->_getClickable($query->result, true) ?>
                    <?php endif ?>
                </td>
            </tr>
            <?php endif ?>
        <?php endforeach ?>
    </tbody>
</table>