<?php foreach ($query->conditions as $condition) { ?>
    <?php $isNested = is_array($condition[0]); ?>
    <tr>
        <th>
            <?php if ($isNested): ?>
                <?php if ($condition[1] === "AND"): ?>
                    whereAre
                <?php else: ?>
                    orWhereAre
                <?php endif ?>
            <?php else: ?>
                <?php if ($condition[3] === "AND"): ?>
                    where
                <?php else: ?>
                    or
                <?php endif ?>
            <?php endif ?>
        </th>
        <td>
            <?php if ($isNested): ?>
               <?php echo $this->getClickable($condition[0], true) ?>
            <?php else: ?>
                <?php echo $condition[0] ?> <?php echo $condition[1] ?> <?php echo $this->getClickable($condition[2], true) ?>
            <?php endif ?>
        </td>
    </tr>
<?php } ?>